### ISSUE TITLE
missing interface ZAFDS_SALES_ORDER_IF

### ISSUE THREAD

**Issue by JohnBugFix** [alwinvandeput/ZAFDS_ADOBE_FORM_DEMO_SUBTOTA#1]
Dear expert.

I got this sample from sap community and i am facing some requirement as you mention in your blog.   could you please also upload the interface used by ZAFDS_SALES_ORDER2?

Many thanks to you.

**Comment by alwinvandeput** [comment]
Hello,

I adjusted the code.
Could you delete the objects in your package and import the package again.
